### ISSUE TITLE
Popup opens to bottom even though there is not enough space

### ISSUE THREAD

**Issue by stefan-spittank** [visusnet/typereact#29]
==Steps to reproduce==
Open the demo page:
https://visusnet.github.io/typereact/

Resize the browser, so that the typereact instance labelled "Many Options" is right above the window border.
Click on this typereact instance.

==Observations==

1. On my machine the popup needs about 2s. to show. This is probably expected, though there is no feedback to the user indicating that the click was triggered and something is happening.
2. Initially the popup open downwards even though there is not enough space. Only after the first interaction with the popup it will flip to the top.
3. The popup has both a horizontal and vertical scrollbar. Scrolling the horizontal scrollbar to the right reveals a second vertical scrollbar hidden behind the first vertical scrollbar.

![typereact](https://user-images.githubusercontent.com/21874591/43198861-5d48eba2-9010-11e8-8a43-60250b7c839d.gif)

**Comment by visusnet** [comment]
Fixed with version 1.2.2.
