### ISSUE TITLE
Cursor Navigation in filtered typeahead seems to be broken

### ISSUE THREAD

**Issue by stefan-spittank** [visusnet/typereact#42]
Steps to reproduce:
1. Open https://visusnet.github.io/typereact/
2. Open the first typeahead (default)
3. Type in an 'i to filter down elements 
4. Use cursor down to navigate to the second element in the popup
=> Error: The third element is highlighted instead of the second.
- Subsequent cursor keys lead to invisible selections or wrong elements being selected
![typereact_filtered_cursor](https://user-images.githubusercontent.com/21874591/44778788-2d5b7e80-ab7e-11e8-82ee-3ffecc233a9b.gif)

**Comment by visusnet** [comment]
Fixed with #51.
