### ISSUE TITLE
Typing in a typeahead with many options is unresponsive

### ISSUE THREAD

**Issue by stefan-spittank** [visusnet/typereact#43]
Steps to reproduce:
1. Open https://visusnet.github.io/typereact/
2. Open the demo typeahead labeled "Many options"
3. Type "10" into the textbox
=> The search is very slow and the typeahead becomes unresponsive

Maybe this is to be expected, but then we might need minTypedCharacters back?

**Comment by visusnet** [comment]
Thanks for reporting. Can you confirm that this behavior only occurs for grouped options?

**Comment by stefan-spittank** [comment]
Yes, didn't realize there were two typeaheads labeled "Many options". Only the grouped one seems to be slow.

**Comment by visusnet** [comment]
Fixed with #51.
