### ISSUE TITLE
Tab-Navigation is broken

### ISSUE THREAD

**Issue by stefan-spittank** [visusnet/typereact#47]
Using the tab-key to navigate through the typeaheads on a page, you need two tabs to get from one element to the other. There seems to be an invisible element receiving the focus inbetween (not yet sure where the focus ends up.
This is also reproducable on the demo page:
https://visusnet.github.io/typereact/
1. Set the focus to first typeahead
2. Press tab
=> Error: no visual indication of where the focus is.
3. Press tab again => the second typeahead receives the focus.

**Comment by visusnet** [comment]
Fixed with #49.
